# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Dougal Shakespeare
title: Researching Music Recommendation and effects upon diveristy
email: dougalshakespeare5@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: DougalShakespe1
github_username:  dshakes90
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: dougal-shakespeare
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
I am a PhD student at the Centre March Bloch's CMB Computational Social Science team in Berlin. 
I am currently working with with RECORDS, a collaborative research project funded through an ANR grant (2020-23) and formed as a partnership with Orange and Deezer.  
My work involves investing the role of algorithmic guidence on popular music streaming platforms, exploring the degree to which diversity may be enhaced or rather, constrained by comutational advances in music recommendation. 



# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Publications 

# Education Section
# educaton_title: Education

#darkmode: true 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
